  apiVersion: apps/v1
  kind: Deployment
  metadata:
     name: user-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: user-app
    template:
      metadata:
        labels:
          app: user-app
      spec:
        containers:
          - name: user-container
            image: ms-user-kubernetes:1.0
            ports:
              - containerPort: 8082
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "prod"
