server:
  port: 8082

spring:
  application:
    name: ms-user-kubernetes
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: test
      password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
     enabled: true
